version: "3"

services:
  oda:
    build:
      context: .
      dockerfile: ./Dockerfile.ubuntu
    container_name: oda-ubuntu
    restart: unless-stopped
    volumes:
      - ./:/app
    working_dir: /app
