name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'
          
      - name: Build Binary for Linux
        run: |
          make build GOARCH=amd64
          tar -czvf "oda-linux-amd64.tar.gz" "oda"
          make build GOARCH=arm64
          tar -czvf "oda-linux-arm64.tar.gz" "oda"

      - uses: actions/upload-artifact@v4
        with:
          name: oda-linux-amd64.tar.gz
          path: oda-linux-amd64.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: oda-linux-arm64.tar.gz
          path: oda-linux-arm64.tar.gz

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'

      - name: Build Binary for macOS
        run: |
          make build GOARCH=amd64 
          tar -czvf "oda-darwin-amd64.tar.gz" "oda"
          make build GOARCH=arm64
          tar -czvf "oda-darwin-arm64.tar.gz" "oda"

      - uses: actions/upload-artifact@v4
        with:
          name: oda-darwin-amd64.tar.gz
          path: oda-darwin-amd64.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: oda-darwin-arm64.tar.gz
          path: oda-darwin-arm64.tar.gz

  create-release:
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/oda-darwin-arm64.tar.gz/oda-darwin-arm64.tar.gz
            artifacts/oda-darwin-amd64.tar.gz/oda-darwin-amd64.tar.gz
            artifacts/oda-linux-amd64.tar.gz/oda-linux-amd64.tar.gz
            artifacts/oda-linux-arm64.tar.gz/oda-linux-arm64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
